### ISSUE TITLE
ユーザー追加のバグ

### ISSUE THREAD

**Issue by Shirashoji** [Yokohama-Miyazawa/Ripple#164]
グループを作成せずにユーザーを追加すると
`The request has been black-holed`
と表示される
![スクリーンショット 2020-03-31 20 16 10](https://user-images.githubusercontent.com/46389417/78020463-77c16480-738c-11ea-8a2e-6e0d8f92f558.png)
![スクリーンショット 2020-03-31 20 17 25](https://user-images.githubusercontent.com/46389417/78020565-a4757c00-738c-11ea-8177-83cc8cf6d0e5.png)
![スクリーンショット 2020-03-31 20 17 33](https://user-images.githubusercontent.com/46389417/78020573-a9d2c680-738c-11ea-8fd9-83451da1df51.png)

**Comment by Shirashoji** [comment]
説明が下手だからスクリーンショットも載せときました

**Comment by Shirashoji** [comment]
コースを追加しようとしても
`The request has been black-holed`
と出る

![スクリーンショット 2020-03-31 22 04 41](https://user-images.githubusercontent.com/46389417/78029485-a135bc80-739b-11ea-89ae-5300aa25ab4d.png)


![スクリーンショット 2020-03-31 22 05 09](https://user-images.githubusercontent.com/46389417/78029517-b3aff600-739b-11ea-8168-33fb442d14b2.png)

**Comment by TachibanaET** [comment]
/tmp/logs/error.log にあるエラーの詳細はどんな感じですか？

**Comment by Shirashoji** [comment]
[error.log](https://github.com/Yokohama-Miyazawa/Ripple/files/4413843/error.log)

**Comment by Shirashoji** [comment]
```
2020-03-31 22:05:04 Error: [SecurityException] '_Token.debug' was not found in request data.
Request URL: /e-learning/Ripple/admin/courses/add
Stack Trace:
#0 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Controller/Component/SecurityComponent.php(490): SecurityComponent->_validToken(Object(CoursesController))
#1 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Controller/Component/SecurityComponent.php(247): SecurityComponent->_validatePost(Object(CoursesController))
#2 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Utility/ObjectCollection.php(129): SecurityComponent->startup(Object(CoursesController))
#3 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#5 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /opt/lampp/htdocs/e-learning/cake/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(CoursesController), Object(CakeRequest))
#7 /opt/lampp/htdocs/e-learning/Ripple/webroot/index.php(187): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

**Comment by Shirashoji** [comment]
こんな感じです

**Comment by TachibanaET** [comment]
![image](https://user-images.githubusercontent.com/25558377/78205888-4eadea80-74d8-11ea-9734-4522a8cdfd69.png)
これを追加してみてください

**Comment by TachibanaET** [comment]
/View/Users/admin_edit.ctpの49行辺りに

**Comment by Shirashoji** [comment]
![スクリーンショット 2020-04-02 17 40 56](https://user-images.githubusercontent.com/46389417/78228009-1d014780-7509-11ea-8013-ba74ab1afb64.png)

できるようになりました．
ありがとうございます．

**Comment by Shirashoji** [comment]
test
