### ISSUE TITLE
CSSの記述が変

### ISSUE THREAD

**Issue by Shirashoji** [Yokohama-Miyazawa/Ripple#202]
[error] webroot/css/custom.css: SyntaxError: CssSyntaxError: Unknown word (27:3)
[error]   25 | .current-setting{
[error]   26 |   margin: 10px;
[error] > 27 |   padding 10px;
[error]      |   ^
[error]   28 | }
[error]   29 | .current-address{
[error]   30 |   font-size: 20px;

**Comment by Yokohama-Miyazawa** [comment]
https://github.com/Yokohama-Miyazawa/Ripple/commit/502807fadf20672dfe4ccad56a61f932da9f65cf で対応しました。

**Comment by Yokohama-Miyazawa** [comment]
https://github.com/Yokohama-Miyazawa/Ripple/commit/502807fadf20672dfe4ccad56a61f932da9f65cf で対応しました。
